name: Cleanup Old Images

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:     # Allows manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install requests
      run: pip install requests

    - name: Run cleanup script
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      run: python cleanup.py
